### ISSUE TITLE
There is not a good pattern for presenting errors to end-users

### ISSUE THREAD

**Issue by bkeepers** [probot/friction#1]
There's not a good way to expose errors to project admins.

For example, if there's a syntax error with the yaml file in `.github/stale.yml`, the [stale](https://github.com/probot/stale) plugin will throw an exception, but it's not currently handled anywhere. To the end-user, it just looks like the plugin is not working.

Here are a few ideas for how we could handle it:

1. Expose an endpoint that runs a "check" to make sure everything looks good and doesn't contain errors. See also https://github.com/probot/probot/issues/187. This works for initial setup or the occasional sanity check, but doesn't help when things go wrong at unexpected times.

1. If the error happens when receiving a Pull Request event, a failing status could be added on the pull request that shows the error.

1. Open an issue on the target repository. Greenkeeper does, this, and it gets pretty [noisy](https://github.com/search?q=label%3Agreenkeeper+%40probot&ref=opensearch).

1. ??? Any other ideas ???

**Comment by anglinb** [comment]
Wow I spent a long time fully collecting my thoughts, never refreshing the issues page and I wrote pretty much the same exact thing plus some specifics 🙃  https://github.com/probot/friction/issues/2

I'll leave the specifics over in that issue and comment the relevant sections here.

**Comment by anglinb** [comment]
Only different thoughts I had on the how to handle specially end user error reporting is as follows:

- Use the number of failed webhook deliveries to show the end user the "health" of all the GitHub Apps they have installed. Similar to status.github.com
- Expose a ping-pong function for `issue_comments`
  - If the plugin listens for comments, allow a special string to act as a ping pong test. [Hubot Example](https://github.com/ropensci/hubot/blob/master/scripts/ping.coffee#L10)

**Comment by johnbillion** [comment]
It's a pity that the GitHub API doesn't expose a means of sending a notification to the user. It would be a good delivery mechanism to alert end users of issues with an app.

**Comment by aergonaut** [comment]
I'm interested in this as well, especially the case of syntax errors in config file or other kinds of invalid config. The app needs some way to alert the owner of the repo that there's a problem and what they could do to fix it. In my case, I have a JSON Schema that describes my app's config file, so ideally I would want to be able to show the repo owner the validation errors in their config file if there's a problem.

It sounds like opening an issue on the repository is the best way to go. But it would also be great if an app had a way to email whatever user installed the app, or if it could email everyone with the repository owner role.

**Comment by dessant** [comment]
@aergonaut, I've had the same problem, having to contact users myself about config errors, so I've made an extension for it. It works by opening an issue for a new message, and optionally posts a reminder comment on the same issue when you call the function with the same message.

I use it [like this](https://github.com/dessant/reaction-comments/blob/104ffddd5c51f16d17ec35b25159d5ce67fb48cc/src/index.js#L93), the message could also include a link to a short [YAML](https://learnxinyminutes.com/docs/yaml/) or [JSON](https://learnxinyminutes.com/docs/json/) tutorial, and a syntax validator.

https://github.com/dessant/probot-messages

<blockquote><img src="https://avatars2.githubusercontent.com/u/7513068?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/dessant/probot-messages">dessant/probot-messages</a></strong></div><div>probot-messages - Probot extension for communicating with repository maintainers</div></blockquote>
