### ISSUE TITLE
Global error handling

### ISSUE THREAD

**Issue by elliotblackburn** [probot/friction#11]
## Scenario

* A user posts an issue on a repo
* The repo listens for new issues and applies tags dependant on issue content. The bot also has other scripts to react to other events.
* The bot encounters an error in the code paths, perhaps a small unhandled use case.

Currently the error must be handled at each point where one can occur (generally one or more per hook). To alert the bot owner that something has gone wrong could be different for different people, some may wish to log the error and remain silent where as others may wish for a notification or some other issue to be raised.

Frameworks such as express tend to forward errors (handled and unhandled) to a global error handler. This gives one easy location to process system errors without having to duplicate code or call the same function in each place. Having some system hook which is triggered on an unhandled exception may make the Ops / SysAdmin side of probot much easier to work with. This way users can also choose to include specific error handling as required, but can fall back to a global handling location as well.

**Comment by elliotblackburn** [comment]
I think this is still a valid point of friction, would be good to get some thoughts from some others.

**Comment by elliotblackburn** [comment]
As said above, this would still be nice to have.

**Comment by bobvanderlinden** [comment]
I was trying to integrate Sentry/Raven into my Probot. It isn't directly trivial what global error handler I can use. I now wrap calls inside each `app.on`, but this is somewhat less than ideal. It's probably possible, because we're building on top of Express, but it's not directly clear.

Should I just `app.use(...)` to wrap everything in an error handler?

**Comment by elliotblackburn** [comment]
This is very much what I'm after solving with this issue, it would be great to have some sort of function hook we can provide that gets called each time there's an unhandled error with information on the error. Other than that, we can only really reply on the javascript unhandled exception event, but I fear these may be technically "handled" by the probot route handlers and this event won't end up getting fired.

**Comment by hassankhan** [comment]
This is still causing friction
