### ISSUE TITLE
Checking if a commit is part of a PR

### ISSUE THREAD

**Issue by JasonEtco** [probot/friction#12]
I may be missing something obvious, and this may be a problem with the API itself, but if I'm listening for `push` events and am dealing with things on a commit, there's no easy way to see if that commit is part of a larger PR (or get the PR number).

I tried this but it doesn't really work:

```js
async function commitIsInPR (context, sha) {
  const prs = await context.github.pullRequests.getAll(context.repo())

  prs.data.forEach(async pr => {
    const commits = await context.github.pullRequests.getCommits(context.repo({number: pr.number}))

    if (commits.data.some(c => c.sha === sha)) {
      return pr.number
    }
  })
  return false
}
```

I think the `push` event happens before the pull request is updated, so the PR wouldn't have the new commit that was sent in the payload `push` event.

---

## Proposed solution

* Ask the GitHub API to please add a `pull_request` property in commit objects? Don't know how hard that would be to implement, but I can see it being useful.

* Build a working version of the above code into Probot

* Build a standalone npm modules that does the above

**Comment by jbjonesjr** [comment]
> * Build a working version of the above code into Probot
> * Build a standalone npm modules that does the above

It seems that the best extension point for something like this would be in `node-github` in some way shape, or form. Right now that library is basically JUST an SDK, but it seems like building out helper functions like this (and dealing with project cards as another example).

An alternative implementation is instead of looking through commits, but instead to compare the branch of the PR head commit to the branch on the commit that was pushed.

code-snippet:
```
prs.data.find(pull => {
      return 'refs/heads/' + pull.head.ref === push.payload.ref;
});
```

**Comment by JasonEtco** [comment]
> It seems that the best extension point for something like this would be in node-github in some way shape, or form.

Agreed; I think that makes sense. I'll open up an issue there soon.

> instead to compare the branch of the PR head commit to the branch on the commit that was pushed.

Interesting! I'll have to try that out tomorrow, thanks!

**Comment by JasonEtco** [comment]
I'm going to close this because @jbjonesjr's solution was 💯 and worked perfectly. Thanks again!
