### ISSUE TITLE
Contact users of GitHub App

### ISSUE THREAD

**Issue by gr2m** [probot/friction#15]
When doing changes to my github app which change the behaviour of it, users have no choice, they will just get the new version. For example the [First Timers](https://probot.github.io/apps/first-timers/) app has a default template when creating its issues: https://github.com/hoodiehq/first-timers-bot/blob/1c0d5e812ac1c088d0fba254422e5767456e79e9/instructions.md

We have ideas on how we could improve these instructions, but it would be quite a big change. It would be great if there would be a good way to reach out to active users of the app to involve them in our decision making and to give them a heads up about the changes :)

Any suggestions?

**Comment by bkeepers** [comment]
This has been an issue for me in the past too. I opened an issue about it with the GitHub Apps team and will let you know if there is any progress.

Workarounds:

- Specify a **Setup URL** that requires the installer to OAuth and fetch [emails](https://developer.github.com/v3/users/emails/#list-email-addresses-for-a-user). Problems: user that installed the app could leave the organization; you don't know which email should be used for the current organization
- Request organization read access, get the [list of members with `role=admin`](https://developer.github.com/v3/orgs/members/#members-list), and get the [public email](https://developer.github.com/v3/users/#get-a-single-user) for each user. Problems: requires additional permissions; public email may be nil.
