### ISSUE TITLE
Create a space for new contributors

### ISSUE THREAD

**Issue by gr2m** [probot/friction#21]
When people come to the Probot community and would like to contribute something, it would be nice to have place that we could point them to. I discussed the idea of a "welcome" repository in the past, which would have documentation for all our processes as well as different kind of contributions that people can do as well as issues that are very well prepared for first-time contributors and as well as more complex issues for people who’d like to take on more ownership.

Specifically I expect to get an influx of people coming trough Google & Rails Girls Summer of Code over the next few weeks

**Comment by gr2m** [comment]
Yeah I think that’s still something I’d like to be addressed eventually

**Comment by abhijeetps** [comment]
It's still a WIP. I think someone is working on it.
