### ISSUE TITLE
Getting started with JavaScript

### ISSUE THREAD

**Issue by bkeepers** [probot/friction#23]
JavaScript is one point of friction that I've heard people often cite in getting started with Probot.  I’d love to include some links for quickly getting up to speed on JavaSCript in the Probot docs.

What are you favorite resources on getting started with JavaScript? Especially ES6 and async/await? Bonus points if they give a concise overview and then allow people to deep dive on specific topics.

**Comment by Nischay-Pro** [comment]
Honestly, Coursera, Udemy, and Codecademy is a solid way to get started with JavaScript. It's interactive, you get to do mini tasks and it has a pretty much detailed explanation of each and everything. 

If you are looking for a textual resource Mozilla's [getting started](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics) is good. 

Btw. Mozilla has a pretty detailed documentation and overview for Async and Await. Might as well add it also.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/async_function

<blockquote><img src="https://cdn.mdn.mozilla.net/static/img/opengraph-logo.72382e605ce3.png" width="48" align="right"><div>MDN Web Docs</div><div><strong><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await">await</a></strong></div><div>The await operator is used to wait for a Promise. It can only be used inside an async function.</div></blockquote>
<blockquote><img src="https://cdn.mdn.mozilla.net/static/img/opengraph-logo.72382e605ce3.png" width="48" align="right"><div>MDN Web Docs</div><div><strong><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/async_function">async function expression</a></strong></div><div>The async function keyword can be used to define async functions inside expressions.</div></blockquote>

**Comment by tcbyrd** [comment]
One of the challenges I had when learning Probot was that even though I had already taken a NodeJS course and was running a functioning web site, the event driven architecture that's inherent to how Probot works wasn't something that was covered. For that part, I found this article from freeCodeCamp very helpful: https://medium.freecodecamp.org/understanding-node-js-event-driven-architecture-223292fcbc2d

For that matter, Free Code Camp's modules are a really great introduction for complete beginners: https://www.freecodecamp.org/

One of my favorite YouTube channels is [FunFunFunction](https://www.youtube.com/channel/UCO1cgjhGzsSYb1rsB4bFe4Q). MPJ posts weekly videos discussing various concepts relevant to JS developers.

For some paid courses that are really well structured, I like [Wes Bos](http://wesbos.com/). He has a free course on vanilla Javascript, but it's more geared towards front-end developers. His paid courses include one on [Node](https://learnnode.com/) and new one that covers [ES6](https://es6.io/).



<blockquote><img src="https://cdn-images-1.medium.com/max/1200/1*Nozl2qd0SV8Uya2CEkF_mg.jpeg" width="48" align="right"><div><img src="https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico" height="14"> freeCodeCamp</div><div><strong><a href="https://medium.freecodecamp.org/understanding-node-js-event-driven-architecture-223292fcbc2d">Understanding Node.js Event-Driven Architecture – freeCodeCamp</a></strong></div><div>Most of Node’s objects — like HTTP requests, responses, and streams — implement the EventEmitter module so they can provide a way to emit…</div></blockquote>
<blockquote><img src="https://s3.amazonaws.com/freecodecamp/curriculum-diagram-full.jpg" width="48" align="right"><div>freeCodeCamp</div><div><strong><a href="https://www.freecodecamp.org">Learn to code with free online courses, programming projects, and interview preparation for developer jobs.</a></strong></div><div>Learn to code with free online courses, programming projects, and interview preparation for developer jobs.</div></blockquote>

**Comment by AshanthaLahiru** [comment]
https://javascript.info/
This is what I used to understand the logic behind the Javascript. It's really good. 

https://www.youtube.com/watch?v=8aGhZQkoFbQ&t=250s 
This video will be helpful to understand the asynchronous behavior of Javascript.

<blockquote><img src="https://javascript.info/img/site_preview_en_1200x630.png" width="48" align="right"><div><strong>The Modern Javascript Tutorial</strong></div></blockquote>

**Comment by bkeepers** [comment]
Great resource on Promises from @itaditya: https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html

**Comment by itaditya** [comment]
This article can help you understand concurrency in javascript https://medium.freecodecamp.org/avoiding-the-async-await-hell-c77a0fb71c4c

<blockquote><img src="https://cdn-images-1.medium.com/max/1200/1*_3nDjjPTWn4ohLt96IcwCA.png" width="48" align="right"><div><img src="https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico" height="14"> freeCodeCamp</div><div><strong><a href="https://medium.freecodecamp.org/avoiding-the-async-await-hell-c77a0fb71c4c">How to avoid (or escape) async/await hell – freeCodeCamp</a></strong></div><div>async/await freed us from callback hell, but people have started abusing it — leading to the birth of async/await hell.</div></blockquote>

**Comment by hiimbex** [comment]
Anyone on this issue interested in doing a bit of writing and curating a list of these resources that we could add to our docs somewhere?

Maybe under the reference section we could have a section 'Getting started with JavaScript' and link to it from https://probot.github.io/docs/  saying 'Never used JavaScript before? Check out our 'Getting started with JavaScript' resources page to help get started!' 

and https://probot.github.io/docs/hello-world with something like 'Is this JavaScript stuff new to you? Check out our 'Getting started with JavaScript' curated resource list!' 

The main list would live in https://github.com/probot/probot/tree/master/docs and I'd be very happy to review any PRs doing this!

<blockquote><img src="https://probot.github.io/assets/card.png" width="48" align="right"><div><img src="/favicon.ico" height="14"> Probot</div><div><strong><a href="https://probot.github.io/docs/">Introduction</a></strong></div><div>GitHub Apps to automate and improve your workflow</div></blockquote>
<blockquote><img src="https://probot.github.io/assets/card.png" width="48" align="right"><div><img src="/favicon.ico" height="14"> Probot</div><div><strong><a href="https://probot.github.io/docs/hello-world/">Hello World</a></strong></div><div>GitHub Apps to automate and improve your workflow</div></blockquote>
<blockquote><img src="https://avatars2.githubusercontent.com/u/26350515?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/probot/probot">probot/probot</a></strong></div><div>probot - 🤖 A framework for building GitHub Apps to automate and improve your workflow</div></blockquote>

**Comment by bdougie** [comment]
Popping in here to add my 2 cents. It doesn't sound ideal to curate a list but seems more ideal to point individuals to existing lists. 

It the most cited friction is node and not JS, perhaps recommending the first few [nodeschool.io](https://nodeschool.io/#workshoppers) workshops in the following order would be ideal. Having an in-person community is a plus as well.
`
[
  " javascripting",
  "learnyounode",
  "how-to-npm"
]
`
