### ISSUE TITLE
Parallelization in probot

### ISSUE THREAD

**Issue by laughedelic** [probot/friction#26]
I've made my first probot: https://github.com/laughedelic/scalafmt-probot, it checks code formatting on every push and reports with commit statuses.

Checking every file one by one can be slow: it fails on the first mis-formatted file, but if everything is fine, it still needs to check all files. I have several ideas how to reduce number of files that it needs to check, but I see an opportunity for an orthogonal improvement: parallelize the checks on several threads. 

I'm new to node.js, so it took me some time to realize that `Promise.all` doesn't do what I want (because node is single-threaded) and I have to fork node instances and manage them manually. While I still can do it, I wanted to ask first if it's the way to go or there is some better way. 

One problem I see at the moment is that IPC allows passing only serializable objects, so I guess I cannot pass an authorized `context.github` instance to the child process. Is there any way I could workaround this limitation?

I'd appreciate any other advices on how to parallelize bot's computations.

**Comment by bkeepers** [comment]
Hey @laughedelic, thanks for the issue.

Node.js really shines when it is handling IO asynchronously. It's not so great with computationally intensive tasks.

I don't have a chance to dive into your code at the moment, but one thing I would suggest is making sure the call to `scalafmt` is handled asynchronously. If it's calling out to a separate process to run the logic, Node should easily be able to spawn the commands and wait for the response and handle it like a champ.

**Comment by laughedelic** [comment]
@bkeepers hi! Thanks for reply.

I read more about multithreading in Node and understand it a bit better now. I need to manage a pool of child processes and a queue of tasks that will be distributed between workers. I see how to deal with it and my question now shifts to this:

> If it's calling out to a separate process to run the logic, Node should easily be able to spawn the commands and wait for the response and handle it like a champ.

While it's easy to factor out the call to scalafmt, I want also to perform requests to Github in parallel: if I have 100 files from a repo to check, I want to parallelize their content retrieval and formatting check (instead of waiting to receive all files first). 

So how can I share the authenticated github client (that I get from `context.github`) between the workers? I guess it's not something serializeable that I can just send over IPC, but probably there is some token that I can send and use it to instantiate new clients in the workers?

**Comment by bkeepers** [comment]
The short answer is you currently can't. But I'm not sure that you need to.

I would recommend doing all the node work in a single process, and passing any information needed for doing work to external processes, and then use the node process to gather the results and post them back to GitHub.

For example:

```js
// Call `map` on the array of things you want to do work on, passing an `async`
// function, and wait for all functions to finish using `Promise.all`. This will allow 
// Each function to do work while other functions are waiting on IO.
await Promise.all(files.map(async path => {
    // Fetch data from GitHub
    const res = await this.github.repos.getContent(context.repo({path}))
    const content = Buffer.from(res.data.content, 'base64').toString()

    // Pass data to external process to do the work.
    // If this function internally uses Promises or callbacks so it does not block.
    // That will allow other functions in this loop to also do their work while Node
    // is waiting on IO from GitHub and your external process.
    const results = await asyncCallToScalaFmt(content);

    // Make GitHub API calls to handle the results.
    return context.github.whateverYouNeedToPostBackToGitHub(results)
}))
```

Hope that helps. Again, Node is incredibly efficient at handling IO-heavy loads, so as long as you call out to other processes when you have blocking work to do, you can parallelize the work. This is much more efficient than spawning a bunch of node processes that are doing blocking work.

**Comment by laughedelic** [comment]
@bkeepers Thank you for the explanation and example. I somehow missed the notification. I will try to follow your advice and see how it works out. In the end I'm probably overthinking it.

**Comment by bkeepers** [comment]
@laughedelic cool, let me know if you have any questions. I'm going to close this since this isn't likely something we'll solve in Probot in the near term.
