### ISSUE TITLE
No well-documented testing methodology

### ISSUE THREAD

**Issue by hiimbex** [probot/friction#3]
It would be great it we could document best practices for testing in a few ways:

- Actual testing as seen here: https://github.com/behaviorbot/update-docs/blob/master/test/index.js
  - Mocking out the GitHub API (practically every plugin
  - Mocking out a probot robot instance `robot = createRobot();` `plugin(robot);`
  - passing the mocked out github method into the robot`robot.auth = () => Promise.resolve(github)`
- All the 
- How best to test plugins/apps
  - We document the simulate command [here](https://github.com/probot/probot/blob/master/docs/plugins.md#simulating-webhooks)
  - I think test driven development is a lot easier than simulating real GitHub events
    - Maybe make this a focus point
    - Factor it in earlier in the docs so people aren't slaving away redelivering webhooks, especially considering the current UI for that is very hard to search
    - Update the existing plugins/apps we use at standards (ie settings, OWNERS, stale etc.) to use best testing practices (or link to my behaviorbot ones 😜)

I'd love to write some of these thoughts up as docs, if you think this seems like a good idea @bkeepers ?

cc/ @luisschubert for testing things!

**Comment by bkeepers** [comment]
> I'd love to write some of these thoughts up as docs, if you think this seems like a good idea @bkeepers ?

Hell yeah!
