### ISSUE TITLE
Webhook events and names are hard to remember

### ISSUE THREAD

**Issue by rsarky** [probot/friction#30]
Currently to find a particular webhook event or name we have to peruse the [ github rest api](https://developer.github.com/v3/) . 

It would be extremely helpful to have a quick reference doc listing out the available webhook events and names. 

cc : @bkeepers @aps120797

**Comment by abhijeetps** [comment]
Here's a gist by @philschatz, we should document some gist in Probot somewhere, would be useful to have a quick view of the same.
It has 101 GitHub events and related actions.
https://gist.github.com/philschatz/d381569d0a4a4a7ce6ba6dac6a065c71

<blockquote><img src="https://avatars1.githubusercontent.com/u/253202?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/philschatz/d381569d0a4a4a7ce6ba6dac6a065c71">probot webhooks and actions</a></strong></div><div>probot webhooks and actions</div></blockquote>

**Comment by abhijeetps** [comment]
Here's another, by @gr2m, https://github.com/octokit/webhooks.js/blob/master/lib/webhook-names.json
It has around 117 events and actions associated with it.


<blockquote><img src="https://avatars0.githubusercontent.com/u/3430433?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/octokit/webhooks.js">octokit/webhooks.js</a></strong></div><div>webhooks.js - GitHub webhook events toolset for Node.js</div></blockquote>

**Comment by abhijeetps** [comment]
Is it possible to create a separate repository on Probot, at one place to look for all possible events and actions associated with the events That can be curated at a common place?

Any updates occurring here ([GitHub Webhook Events](https://developer.github.com/webhooks/#events)) can be later checked while we explore more and receive further updates on the same. 

The most important function of Probot Framework, `robot.on()` heavily depends on it. 😄

**Comment by rsarky** [comment]
I was thinking a new page in the [probot docs](https://probot.github.io/docs/) would be more appropriate? 
What do you think @aps120797 ?

**Comment by itaditya** [comment]
I agree @rsarky, listing all events on probot docs would be better

**Comment by pranay414** [comment]
Yes we should create a new page in probot docs. @rsarky @aps120797

**Comment by abhijeetps** [comment]
Hey @bkeepers , @rsarky ,  @itaditya ,  @pranay414 , I guess I have fixed the problem: https://github.com/probot/probot/pull/498

**Comment by abhijeetps** [comment]
It's still a WIP.

**Comment by bobvanderlinden** [comment]
We should have type information for these arguments. That way they are autocompleted in TypeScript and people do not have to remember them. In addition, it avoids errors due to typos and similar problems.
