### ISSUE TITLE
Finalize the terminology used by probot community.

### ISSUE THREAD

**Issue by itaditya** [probot/friction#32]
Hi I have been digging through some probot repos and I found a small pain point. There have been different terminologies used to describe the same thing.

Example - [`scheduler`](https://github.com/probot/scheduler) describes itself as a helper whereas [`metadata`](https://github.com/probot/metadata) describes itself as an extension.

Is there a difference between an extension / plugin / helper ?

Also as mentioned in https://github.com/probot/no-response/issues/20 , the description uses the term github integration instead of github app. 

All these things lead to slight confusion especially for new contributors. I think we should finalize all the terminologies and consistently use them everywhere.

**Comment by bkeepers** [comment]
Thanks @itaditya. 

> Is there a difference between an extension / plugin / helper ?

We attempted to clarify this in https://github.com/probot/probot/pull/210, but looks like there are still a few paces that are outdated. I updated the description on scheduler.

> Also as mentioned in probot/no-response#20 , the description uses the term github integration instead of github app.

"GitHub Apps" used to be called "GitHub Integrations". https://github.com/probot/probot/pull/154 updated Probot's usage. Feel free to submit pull requests to update anything you see that is out of date.

**Comment by itaditya** [comment]
:+1:

**Comment by abhijeetps** [comment]
For addition details, see this: https://blog.github.com/2017-05-22-introducing-github-marketplace-and-more-tools-to-customize-your-workflow/#github-apps

<blockquote><img src="https://cloud.githubusercontent.com/assets/6165035/25911854/2a7f74ea-356a-11e7-9532-df7fa695a6d8.png" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> The GitHub Blog</div><div><strong><a href="https://blog.github.com/2017-05-22-introducing-github-marketplace-and-more-tools-to-customize-your-workflow/">Introducing GitHub Marketplace and more tools to customize your workflow</a></strong></div><div>Today, we’re building on our launches at GitHub Universe 2016—making it easier than ever to evolve and customize your workflow. Find integrations and put them to work in minutes with GitHub Marketplace, pair developer tools and fine-grained repository permissions with GitHub Apps, or build the exact tool you need with a new, production-ready version of our GraphQL API. Together, these tools give you everything you need to set up a custom workflow that grows with your goals.</div></blockquote>
