### ISSUE TITLE
helpers for tests

### ISSUE THREAD

**Issue by ocombe** [probot/friction#33]
I feel like it's too hard to test probot functions for now. Nock is hard to use and requires a lot of boilerplate.
It would be nice to have some testing functions that does all of that and let us focus on the logic

**Comment by ocombe** [comment]
yes

**Comment by bkeepers** [comment]
Yes, it is, and I completely agree.

**Comment by ocombe** [comment]
yes

**Comment by ocombe** [comment]
Yes still the same
