### ISSUE TITLE
don't know what api is accessed as installation and what as an app

### ISSUE THREAD

**Issue by itaditya** [probot/friction#38]
Hi, while using a github app, for some APIs I have to do `contex.github()` i.e. use a installation authenticated client and sometimes I have to do 
```js
const authenticatedAsApp = await robot.auth()
```
i.e. an app authenticated client. It is very difficult to find out which api resource is accessible as what. Is there any docs I can refer. Please help

**Comment by hiimbex** [comment]
[Authenticating as a GitHub App](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) is very limited in what you can do. You can only:
* You can retrieve high-level management information about your GitHub App.
* You can request access tokens for an installation of the app.

When [authenticated as an installation](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-an-installation) you can use any APIs that are enabled for GH Apps, such as opening issues, using the Checks API, etc.

I just found an issue in the docs thanks to this!
