### ISSUE TITLE
NPM's package-lock.json files are annoying

### ISSUE THREAD

**Issue by bkeepers** [probot/friction#4]
I feel like I'm constantly fighting with NPM@5's package-lock.json file. I often struggle to get the right version of a dependency installed/updated, and I had to disable [GreenKeeper](https://greenkeeper.io/) and am currently [jump through a bunch of hoops](https://github.com/greenkeeperio/greenkeeper-lockfile) to get it working again.

I feel like there's not as much value to the package-lock.json for a project like probot. Is there any reason not to disable it?

cc @gr2m

**Comment by gr2m** [comment]
did you have any problems after you’ve setup `greenkeeper-lockfile`? I’d love to hear about it.

I think we will be fine without a lockfile for now, as probot will is more of a library than an app. And if you have Greenkeeeper enabled and all dependencies are kept up-to-date then things shouldn’t break for contributors / users too much. So you have my plus one on removing package-lock.json, but let’s chat first, I’d love to hear more about your pains and see if there is something I can help with

**Comment by bkeepers** [comment]
> did you have any problems after you’ve setup `greenkeeper-lockfile`? I’d love to hear about it.

I got it set up, but there's not really an easy way to test it (that I could figure out), so I have no clue if it's working. We'll find out with the next release I guess.

**Comment by gr2m** [comment]
I am adding package-lockfile.json to `.gitignore` in my projects. If you have greenkeeper installed, than you won’t have the problem of randomly broken builds that much, so it can as well not be commited at all. Saves us merge conflicts and makes the Greenkeeper integration simpler

**Comment by jarrodldavis** [comment]
Honestly I think I'll do the same for mine. On a couple of the npm-using projects at work, the lockfile seems to randomly change for no reason without changing dependencies resulting in annoying "npm churn" commits. So far I've been manually deleting it with a "I'll deal with it later" attitude and so far I haven't had anything bad happen…

**Comment by hiimbex** [comment]
I think it makes sense to ignore them until something like https://github.com/npm/npm/issues/18007 happens.

**Comment by bkeepers** [comment]
They've all been removed in https://github.com/probot/probot/issues/291
