### ISSUE TITLE
Better error messaging for missing PEM && env vars

### ISSUE THREAD

**Issue by JasonEtco** [probot/friction#7]
Per a discussion going on in the Slack channel [right here](https://probot-talk.slack.com/archives/C6S4FC8AF/p1506048278000092), a user was having a hard time debugging and getting their App going but had no idea why. The error messages being returned weren't too helpful. Turns out, they had forgotten to copy the `.pem` certificate file over to the App's directory. Let's improve the error messaging there (and maybe around other env variables missing)! Could just do something simple like:

```js
const requiredEnvVariables = ['APP_ID', 'OTHER_THING'];
const missingEnvVariables = requiredEnvVariables.filter((v) => Boolean(process.env[v]);

missingEnvVariables.forEach((variable) => {
  console.error(`You are missing the ${variable} environment variable!`);
});
```

cc @anglinb who helped the dev debug this 🙌

**Comment by anglinb** [comment]
Thanks for opening this up @JasonEtco! This super concise and I think would help folks out a bunch when they're getting started. 👍 Could even link to setup docs. I really like how FB does this sort of thing for React Native. If something is broken, they point you to an issue on GitHub that has multiple solutions from the community. I think this is easier to point to docs b/c the "problem" the developer is facing _should_ be easier to fix and it's not a "it could be x, y, or z" type issue where pointing to issues is most helpful.

**Comment by bkeepers** [comment]
Yes, love it!

It'd also be nice to rescue [this error](https://probot-talk.slack.com/archives/C6S4FC8AF/p1506051088000030) with a more friendly error. Something like: `It looks like your private key is not valid. See https//probot.github.io/docs/errors/#invalid-private-key to debug it. OpenSSL says: error:0906D06C:PEM routines:PEM_read_bio:no start`

**Comment by JasonEtco** [comment]
I'd like to open this one up as a `hacktoberfest` issue; shall I make a new one in the [probot/probot](https://github.com/probot/probot) or make the label here?

**Comment by bkeepers** [comment]
New one in probot/probot makes sense to me.
