### ISSUE TITLE
Programmatic access for starting probot

### ISSUE THREAD

**Issue by elliotblackburn** [probot/friction#8]
Currently probot can only be started up via the command line, one could go forward and re-create the CLI boot up process but this seems unfriendly and awkward. It would be really great if there was some way to require in probot and start it up programatically.

## Basic example

```js
const probot = require('probot');
const express = require('express');

const robot = probot({/*options*/}); // Returns an Express Application perhaps

const server = express();
// Configure more of the server, mount a few more things...

server.use(robot);

server.listen(8080);
```

## Use cases

Probot is great stand alone, but could also be really useful as a component, particulary when automating large processes where you wish to also hook into other systems (hubot for example). Since probot runs on Express (I believe), you could return an instance or the Express Application (and maybe the robot and a few other things) which could then be mounted to another Express app and such. This would at least be great when looking to build automation systems which hook into github and other services, and would make hosting multiple services on one heroku instance really easy (and cheaper).

It would also open the gate for a bit more code sharing as well between various parts of a more complex system.

**Comment by elliotblackburn** [comment]
I've unfortunately not had the time to pay with hubot much recently, however by the lack of connected PR's / issues I expect this is still relevant. If it's no longer relevant then please feel free to close it!

**Comment by JasonEtco** [comment]
This is already possible. The code being run in `probot run` is basically doing ☝️. Here's an example of how you could write your own:

```js
const program = {
  id: process.env.APP_ID,
  port: process.env.PORT || 3000,
  tunnel: process.env.SUBDOMAIN || process.env.NODE_ENV !== 'production',
  secret: process.env.WEBHOOK_SECRET,
  clientid: process.env.CLIENT_ID,
  clientsecret: process.env.CLIENT_SECRET
}

const cert = getPrivateKey()
const probot = createProbot({ ...program, cert })

const myExpressApp = probot.server
myExpressApp.get('...')
```

If this works for you, feel free to close this issue.

**Comment by itaditya** [comment]
@JasonEtco thanks

**Comment by elliotblackburn** [comment]
@JasonEtco awesome, glad to see this made it in at some point. When I originally opened the issue `createProbot` wasn't something that was exposed. This looks like the most appropriate way to do it so I'll close the issue, though it would be good if this was documented. I'll see if I can submit a PR for some relevant documentation with a similar example to the one above. Thanks 😄
